language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install: pip install -r requirements.txt
script: python -m unittest discover -s .
notifications:
  slack:
    rooms:
    - secure: eSEgSyauTnmzYy4KHS7ZX+CsxP0ts9UKez2BtL1qntVibH9nTGcGIgt+llw5O99q7+UspUWl2SpyuEpgkpgcJ0Hbuu+vAIQXXLj2hCQGQi17wcjJWXci4z7azxYtS+wqeFUQJ8gS7GEzwFWGiHXvhdeAbddlPAOAXwEF/6IrFQBIx8CGqmVjFb11GRJZAGhaCoYAJjwvPGNIAQWHyH4E2E4cJTbbcc3A0bneMy7jPVOH9L6quTPh8KMn5S0jtoRgU/o22huqx1GQevZCTjUn8p0/khpzIbxLKU9ltnTCOG5L3FSYKdaR7JYNzDrCsz4Bwd0vRCTGj7fhhYWPqs10DFbD+J26BRhymd6742Ah3ex6kqQj+lesaKfOZ9L4opxQfYl69BaQdko+x+LtOJJ7oDAwscKkxvhJ6kExTLwFyo2w0ikV1vDxOoXgiBlZLzIOnwOxIjIotOgnzxBu4KJV+PCs24cJStVJNC+h3MaSgC2JEtE/WRrlZ4sh6/GBf9jrMKgC9ydVfz+eTqlu/USI2kzC4hZIQuM+65OETR/6Ef/T8BJlCsiv5FSDxtkeyGA315ZFrr2lcXi9WaoE8XJ8SGuz4xbCmEkzbNz6YSbHtvKhwMTf0bLh398oppIY3KNltNEoI0ujcZfrbmhWIGk0AaS07UQ4lB4PLjuhWCQKdDc=
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: nutshellfool
  password:
    secure: WgkFmKi0a60s/eAr+0Kjifnv18qUI76TJq56x8b3C+hj4LfQXrC+3MzrS9uyKXi/BbywdW/sgdXmZOFJg1mFbEpZ/aJzG7lgskQUYECJJBO6THBXErmp0NUP8ZjtRRBv+MrE5w4f6TaNZ20Fa/M/NmHHpRiFWs8YvF7BgjwQFdqRT20zhmjAkLP/LcghyzcURX7OBr0Kgmoy4PPtWTMFEvTutiOGbj601fgdRQngoP+059N6YQrclnxfscoFmyOzFP6y8AQzahyO5rkkXCLzIDpp22JH36aU/vTZ0g9nB4t9/JArH/z/6Ve3GWVlNj5JtmZb1b8+ZItMzqHM5mEdsZ9YQcWjmfrJvxqkRnnMt07IAid/RGPZd3L6iMYVqtC10e/n9v3ky1D6MO5vOF5rgf6XDBldvkqy9HQBVtcVs5hsG82JChm7u8mM2dbu3djJ1aR7wPw1d7oDekgteINA5CKpzZPEVm/obqPzP1Q4pD/w8cnoyAK0QAp5rzsUGQuaNNfI4/ut1gGwbvL2VoXTf0vDc8oySTbhFdyuu58GbtOJ3bzy6AmRL36pXvLVzf3dkELgSWDLyaosXy6ejuPFG+lq/YYKAgQeLYtBIIQGwZlcSUdMq1vqdfDuJoTAFoM2L2x0R5/QvIzHa28iwNKWzHfcEReBTGod5m24MuVrYLU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: nutshellfool/addit